# tuned
sac:
  env: brax/ant
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1_000_000
  fill_buffer: 10_000
  batch_size: 512
  learning_rate: 0.00012002827428180874
  num_epochs: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.95
  polyak: 0.99
  target_entropy_ratio: 0
  normalize_observations: true


# tuned
ppo:
  env: brax/ant
  agent_kwargs:
    activation: tanh
  num_envs: 64
  num_steps: 64
  num_epochs: 8
  num_minibatches: 16
  learning_rate: 0.00010838581269344756
  max_grad_norm: 0.5
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.98
  gae_lambda: 0.8
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true
