# tuned
sac:
  env: brax/pusher
  env_params:
    episode_length: 100
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1_000_000
  fill_buffer: 10_000
  batch_size: 512
  learning_rate: 0.00020495107742294415
  num_epochs: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.98
  polyak: 0.995
  target_entropy_ratio: 0
  normalize_observations: true


# tuned
ppo:
  env: brax/pusher
  env_params:
    episode_length: 100
  agent_kwargs:
    activation: tanh
  num_envs: 128
  num_steps: 128
  num_epochs: 8
  num_minibatches: 64
  learning_rate: 0.00027520696850790545
  max_grad_norm: 0.1
  total_timesteps: 1048576
  eval_freq: 32768
  gamma: 0.95
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true

mpo:
  env: brax/pusher
  env_params:
    backend: mjx
  agent_kwargs:
    activation: relu
    hidden_layer_sizes: [256, 256]
  num_envs: 256
  buffer_size: 250_000
  learning_rate: 0.00001077637412410775
  dual_learning_rate: 0.006526550333121093
  max_grad_norm: 100
  total_timesteps: 1_000_000
  eval_freq: 50_000
  gamma: 0.99
  epsilon: 0.03
  epsilon_mean: 0.005577380555553466
  epsilon_stddev: 0.00025792129152668033
  epsilon_penalty: 0.003640854934966809
  num_epochs: 4
  target_update_freq: 1
  normalize_observations: true
