# tuned
sac:
  env: brax/reacher
  env_params:
    episode_length: 50
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1_000_000
  fill_buffer: 10_000
  batch_size: 512
  learning_rate: 0.0004617429169256732
  num_epochs: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.95
  polyak: 0.99
  target_entropy_ratio: 0
  normalize_observations: true


# tuned
ppo:
  env: brax/reacher
  env_params:
    episode_length: 50
  agent_kwargs:
    activation: tanh
  num_envs: 128
  num_steps: 128
  num_epochs: 8
  num_minibatches: 64
  learning_rate: 0.00027520696850790545
  max_grad_norm: 0.1
  total_timesteps: 1048576
  eval_freq: 32768
  gamma: 0.95
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true

mpo:
  env: brax/reacher
  env_params:
    backend: mjx
  agent_kwargs:
    activation: tanh
    hidden_layer_sizes: [256, 256]
  num_envs: 64
  buffer_size: 500_000
  batch_size: 512
  learning_rate: 0.00009410288894084897
  dual_learning_rate: 0.02089659177503632
  max_grad_norm: 1
  total_timesteps: 1_000_000
  eval_freq: 50_000
  gamma: 0.99
  epsilon: 0.3
  epsilon_mean: 0.003808296710796426
  epsilon_stddev: 0.0005330257926628397
  epsilon_penalty: 0.004359787694098387
  action_penalization: false
  num_action_samples: 40
  policy_eval_num_val_samples: 32
  num_epochs: 4
  polyak: 0.99
  target_update_freq: 1
  normalize_observations: true
