sac:
  env: navix/Navix-FourRooms-v0
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 131_072
  fill_buffer: 8_192
  batch_size: 256
  learning_rate: 0.0003
  num_epochs: 128
  total_timesteps: 1_048_576
  eval_freq: 131_072
  gamma: 0.9
  polyak: 0.995
  target_entropy_ratio: 0.9
  normalize_observations: false

ppo:
  env: navix/Navix-FourRooms-v0
  agent_kwargs:
    activation: swish
  num_envs: 128
  num_steps: 32
  num_epochs: 2
  num_minibatches: 8
  learning_rate: 0.0003
  max_grad_norm: 5
  total_timesteps: 1_048_576
  eval_freq: 262_144
  gamma: 0.99
  gae_lambda: 0.99
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: false

dqn:
  env: navix/Navix-FourRooms-v0
  agent_kwargs:
    activation: relu
  num_envs: 128
  num_epochs: 128
  buffer_size: 131_072
  fill_buffer: 8_192
  batch_size: 256
  learning_rate: 0.0003
  max_grad_norm: 10
  total_timesteps: 1_048_576
  eval_freq: 131_072
  gamma: 0.9
  eps_start: 1.0
  eps_end: 0.01
  exploration_fraction: 0.1
  target_update_freq: 2_048
  ddqn: true
  normalize_observations: false

iqn:
  env: navix/Navix-FourRooms-v0
  agent_kwargs:
    activation: relu
  num_envs: 128
  num_epochs: 128
  buffer_size: 131072
  fill_buffer: 8192
  batch_size: 512
  learning_rate: 0.0003
  kappa: 2.0
  num_tau_samples: 32
  num_tau_prime_samples: 16
  total_timesteps: 1048576
  eval_freq: 131072
  gamma: 0.95
  eps_start: 1.0
  eps_end: 0.05
  exploration_fraction: 0.7
  target_update_freq: 512
  normalize_observations: false

pqn:
  env: navix/Navix-FourRooms-v0
  total_timesteps: 1048576
  eval_freq: 262144
  eps_start: 1
  num_envs: 32
  num_steps: 512
  num_epochs: 1
  num_minibatches: 128
  learning_rate: 0.00017855922645162287
  max_grad_norm: 10
  eps_end: 0.05
  exploration_fraction: 0.7
  gamma: 0.99
  td_lambda: 0.4
  normalize_observations: true
